[package]
name = "xgrammar-rs"
version = "0.1.27"
edition = "2024"
build = "build.rs"
links = "xgrammar"
authors = ["Eugene Bokhan <eugenebokhan@gmail.com>"]
description = "Efficient, Flexible and Portable Structured Generation for Rust - Rust bindings for XGrammar"
license = "Apache-2.0"
repository = "https://github.com/trymirai/xgrammar-rs"
homepage = "https://github.com/trymirai/xgrammar-rs"
documentation = "https://docs.rs/xgrammar-rs"
readme = "README.md"
keywords = ["llm", "grammar", "structured-gen", "json-schema", "parser"]
categories = ["parsing", "text-processing"]

[lib]
name = "xgrammar"

[dependencies]
autocxx = "0.30.0"
cxx = "1.0.187"
serde_json = "1.0.145"

[build-dependencies]
walkdir = "2.5.0"
cmake = "0.1.54"
autocxx-build = "0.30.0"

[dev-dependencies]
schemars = "1.1.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
serial_test = "3.2.0"

[features]
default = []
tokenizers = ["dep:tokenizers"]
hf = ["tokenizers", "dep:hf-hub"]

[dependencies.tokenizers]
version = "0.22.1"
optional = true

[dependencies.hf-hub]
version = "0.4.3"
optional = true
