[package]
name = "xgrammar"
version = "0.1.0"
edition = "2024"
build = "build.rs"
links = "xgrammar"

[dependencies]
autocxx = "0.30.0"
cxx = "1.0.187"

[build-dependencies]
walkdir = "2.5.0"
cmake = "0.1.54"
autocxx-build = "0.30.0"

[dev-dependencies]
schemars = "1.0.4"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
