[package]
name = "xgrammar-rs"
version = "0.1.0"
edition = "2024"
build = "build.rs"
links = "xgrammar"

[dependencies]
cxx = "1.0.184"

[build-dependencies]
walkdir = "2.5.0"
cmake = "0.1.54"
cxx-build = "1.0.184"
